version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
    groups:
      dev-dependencies:
        dependency-type: development
    labels: [dependencies]
    commit-message:
      prefix: chore
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    labels: [dependencies]
    commit-message:
      prefix: chore
